apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: muchtodo
type: Opaque
stringData:
   MONGO_INITDB_ROOT_USERNAME: bXVjaHRvZG8=  # Base64 encoded value of "muchtodo"
   MONGO_INITDB_ROOT_PASSWORD: c2VjdXJlUGFzc3dvcmQ=  # Base64 encoded value of "securePassword"