apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: muchtodo
spec:
  type: ClusterIP
  selector:
    app: muchtodo-backend
  ports:
    - port: 8080
      targetPort: 8080
    
  
